# Generated by Django 5.1.7 on 2025-06-06 08:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_number', models.CharField(max_length=10, unique=True, verbose_name='№ читателя')),
                ('registration_year', models.IntegerField(verbose_name='Год регистрации')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Домашний адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('school_class', models.CharField(max_length=10, verbose_name='Класс')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID Telegram')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сотрудник')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(default=datetime.datetime(2025, 6, 20, 8, 27, 51, 553277, tzinfo=datetime.timezone.utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.reader')),
            ],
        ),
        migrations.CreateModel(
            name='BookFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.reader')),
            ],
            options={
                'unique_together': {('reader', 'book')},
            },
        ),
    ]
