# Generated by Django 5.1.7 on 2025-04-09 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID Telegram'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 5, 12, 2, 623417, tzinfo=datetime.timezone.utc)),
        ),
    ]
