# Generated by Django 5.1.7 on 2025-06-06 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='reader_number',
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 8, 40, 38, 274241, tzinfo=datetime.timezone.utc)),
        ),
    ]
