# Generated by Django 5.1.7 on 2025-06-07 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_reader_reader_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 13, 58, 44, 789193, tzinfo=datetime.timezone.utc)),
        ),
    ]
