# Generated by Django 5.1.7 on 2025-06-07 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_inventory_number_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 14, 7, 12, 893803, tzinfo=datetime.timezone.utc)),
        ),
    ]
