# Generated by Django 5.1.7 on 2025-04-14 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookissue_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 28, 5, 36, 29, 739315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
