# Generated by Django 5.1.7 on 2025-06-07 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_inventory_prefix_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 21, 14, 46, 58, 760673, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='books.book')),
            ],
        ),
    ]
