# Generated by Django 5.1.7 on 2025-06-08 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookissue_inventory_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fund_type',
            field=models.CharField(choices=[('fiction', 'Художественный'), ('educational', 'Учебный'), ('reference', 'Справочный')], default='fiction', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 8, 27, 28, 819389, tzinfo=datetime.timezone.utc)),
        ),
    ]
