# Generated by Django 5.1.7 on 2025-06-08 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_fund_type_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращена'),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='returned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 11, 56, 53, 461709, tzinfo=datetime.timezone.utc)),
        ),
    ]
