# Generated by Django 5.1.7 on 2025-06-12 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookissue_is_returned_bookissue_returned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма поступления'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник поступления'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 15, 42, 47, 380966, tzinfo=datetime.timezone.utc)),
        ),
    ]
