# Generated by Django 5.1.7 on 2025-06-12 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookinstance_amount_bookinstance_receipt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='source',
        ),
        migrations.AddField(
            model_name='book',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='book',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма поступления'),
        ),
        migrations.AddField(
            model_name='book',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Источник поступления'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 16, 22, 43, 4474, tzinfo=datetime.timezone.utc)),
        ),
    ]
