# Generated by Django 5.1.7 on 2025-06-13 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_bookinstance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='inventory_digit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 27, 5, 45, 53, 575242, tzinfo=datetime.timezone.utc)),
        ),
    ]
