# Generated by Django 5.1.7 on 2025-06-13 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_batch_number_book_inventory_digit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 27, 7, 51, 22, 327585, tzinfo=datetime.timezone.utc)),
        ),
    ]
