# Generated by Django 5.1.7 on 2025-06-13 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_bookissue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за экземпляр'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 27, 9, 3, 49, 822113, tzinfo=datetime.timezone.utc)),
        ),
    ]
